server {
    listen 80;
    server_name _;

    # Forward requests to /api to the backend
    location ~* /api {
        proxy_pass http://backend:3000;
    }
    
    # Forward other requests to the frontend
    location / {
        proxy_pass http://frontend:80;
    }
}